# WARNING: This compose file is for LEARNING ONLY
# Use docker-compose.malware-secure.yml for actual malware analysis

services:
  kali-malware:
    build:
      context: .
      dockerfile: docker/base/Dockerfile
    image: kali-custom:latest
    container_name: kali-malware-isolated
    hostname: malware-lab
    environment:
      - DISPLAY=host.docker.internal:0
      - DEBIAN_FRONTEND=noninteractive
      - CLAUDE_AUTH_METHOD=${CLAUDE_AUTH_METHOD:-}
    volumes:
      - ./malware/samples:/home/kali/malware-analysis/samples:ro
      - ./malware/reports:/home/kali/malware-analysis/reports
      - ./config:/home/kali/.config
      - ./scripts:/home/kali/scripts:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/home/kali/.Xauthority:rw
    network_mode: none
    privileged: true
    stdin_open: true
    tty: true
    restart: unless-stopped
    mem_limit: 4g
    cpus: 2
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
      - NET_RAW